module.exports = {
    homeRoute: '/home',
    adminRoute: '/chimp-admin',
    // Marketing routes listed here kick out to the railsAppUrlOrigin
    marketingRoutes: [
        '/',
        '/home',
        '/2015',
        '/about',
        '/accounts',
        '/brand',
        '/careers',
        '/charities',
        '/chimp-account-agreement',
        '/chimp-foundation',
        '/community-account-agreement',
        '/community',
        '/contact',
        '/discover',
        '/education',
        '/events',
        '/families',
        '/fees',
        '/funding-organizations',
        '/fundraising',
        '/get-started',
        '/giving-groups',
        '/individuals',
        '/investment-account-agreement',
        '/matchco-agreement',
        '/our-story',
        '/philanthropists',
        '/press',
        '/privacy',
        '/qualified-recipient-agreement',
        '/sports',
        '/team',
        '/terms',
        '/trust',
        '/types-of-donations',
        '/ways-to-give',
        '/workplace',
    ],
}
